### ISSUE TITLE
Debounce after 5 seconds

### ISSUE THREAD

**Issue by waygou** [emilianotisato/nova-google-autocomplete-field#2]
Hi,

Thanks for building this field, it have a lot of potential to be used widely!

Still, I think there is an enhancement that will allow the google places api quota (for free usage) not to be exceeded so fast, in case you can use a debounce option.

Meaning, you should only send the request when the user "stops writing in the field after X seconds".

User starts writing the address.
Then he stops writing.
Field waits 5 seconds.
Then makes the HTTP call.

This would reduce drastically the usage of the HTTP requests to the Google places API.

Thanks,
Bruno

**Comment by emilianotisato** [comment]
Hello @waygou ,

You are right. You can send me a PR, or wait a few days til I make the change...

Thanks

Emiliano

**Comment by waygou** [comment]
Thanks! And no worries, I can wait since I'm working on other parts of my project atm.

Cheers,
Bruno

**Comment by emilianotisato** [comment]
Ok, @waygou ,

Since this package is based on [olefirenko/vue-google-autocomplete](https://github.com/olefirenko/vue-google-autocomplete) packages.

I am participating [on this discussion](https://github.com/olefirenko/vue-google-autocomplete/issues/82). Because at this moment I don't see how can I implement this "delaying" feature...
